### ISSUE TITLE
Define upper level structures in XSD

### ISSUE THREAD

**Issue by ppazos** [openEHR/specifications-ITS-REST#11] opened 2016-06-07 01:16 UTC
Did anyone defined an XSD for EHR, EHR_STATUS and FOLDER?

I think we need at least those for v0.1.

A related question: what do you think about the inclusion of EHR_ACCESS as a structure that will be used in the API?

IMO I don't think we should include it if no one uses it to model access constraints to the EHR, in fact I don't know many implementations that use that class, but maybe others do.

I think later we'll need to define also all the VERSIONED_XXX classes in the XSD. That would help a lot on use cases that require migration of data (for example, allowing to export/import full versioned compositions between systems, for backup, for redundancy / HA, etc).

Does anyone already represented the VERSIONED_XXX classes in XSD?

**Comment by ppazos** [comment] 2016-06-22 15:17
If nobody did this, I will add it to the XSD and share the update.

**Comment by sebastian-iancu** [comment] 2016-06-22 15:53
If you are ok with that, please upload them via (a new) JIRA issue or you can send it to me - I need to maintain the ITS-XSD files on github / Jira.

**Comment by ErikSundvall** [comment] 2016-06-23 15:02
Is this a duplicate of #4 ? I am reposting my reply from #4 here so that we can Close #4 if we want to.
- - -

In the directory https://github.com/LiU-IMT/EEE/tree/master/src/main/xsd you can find the (not so well tested) XML-schemas from LiU EEE. Feel free to reuse, modify and comoment. Highlights:

- EHR: https://github.com/LiU-IMT/EEE/blob/master/src/main/xsd/EEE-flat-storage-v1.xsd (other structures are possible, and for nested storage I think we used a slightly different approach, will try to find it)
- CONTRIBUTION, EHR_STATUS, EHR_ACCESS, VERSIONED_OBJECTs etc: https://github.com/LiU-IMT/EEE/blob/master/src/main/xsd/EEE-v1.xsd (note that the CotributionBuild class in that file will likely not be part of the current API we are specifying now, maybe rather in a later separate optional spec)
- XML-based query result: https://github.com/LiU-IMT/EEE/blob/master/src/main/xsd/xml-result-v1.xsd

**Comment by ppazos** [comment] 2016-06-24 06:00
@ErikSundvall @sebastian-iancu analyzing the XSD and the model I detected the XSD allowed empty values on some datatypes where the IM had invariants that said otherwise.

My XSD is a merge of all the different XSD files published by openEHR. Here are my commits with the changes. Please let me know what you think. Check Verssion.xsd

https://github.com/ppazos/cabolabs-ehrserver/commit/3551203d5a09439590f73d8b201c6eb5dd86fdf3
https://github.com/ppazos/cabolabs-ehrserver/commit/43a395ac74e7e8787ea1c1deade6788c4ce8b034

I will check the XSDs shared by @ErikSundvall thanks!

**Comment by ppazos** [comment] 2016-06-30 05:04
@ErikSundvall trying to load https://raw.githubusercontent.com/LiU-IMT/EEE/master/src/main/xsd/EEE-flat-storage-v1.xsd

On http://visualxsd.com/ and http://xsd2xml.com/

I get

There's some problem with schema, you're trying to view:
The complexType 'http://schemas.openehr.org/v1:DATA_VALUE' has already been declared.

I tried commenting the references but I couldn't find the issue.

**Comment by ppazos** [comment] 2016-07-11 21:14
@ErikSundvall did you had the change to take a look at ^ ?

**Comment by sebastian-iancu** [comment] 2018-11-14 22:47
XSD related work i snow done under specifications-ITS-XML repo

**Closed by sebastian-iancu** 2018-11-14 22:47 UTC
Labels: discussion
